# -*- coding: utf-8 -*-
"""Credit Portfolio Data Analysis Script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mx5jnjgLRxMQJcQ2GlrP_T9vV2eGc4Xn
"""

import pandas as pd
import numpy as np
import zipfile
import os

"""## Data Profiling and Cleaning"""

with zipfile.ZipFile('/content/Credit Data (1).zip', 'r') as zip_ref:
    zip_ref.extractall('credit_data')

credit_data_jan = pd.read_csv("/content/credit_data/Credit Data/Credit Data - 01-01-2025.csv")
credit_data_jan.head(5)

credit_data_jan.info()

credit_data_march = pd.read_csv("/content/credit_data/Credit Data/Credit Data - 30-03-2025.csv")
credit_data_march.head(5)

credit_data_march.info()

credit_data_june = pd.read_csv("/content/credit_data/Credit Data/Credit Data - 30-06-2025.csv")
credit_data_june.head(5)

credit_data_june.info()

credit_data_sep = pd.read_csv("/content/credit_data/Credit Data/Credit Data - 30-09-2025.csv")
credit_data_sep.head(5)

credit_data_sep.info()

credit_data_dec = pd.read_csv("/content/credit_data/Credit Data/Credit Data - 30-12-2025.csv")
credit_data_dec.head(5)

credit_data_dec.info()

credit_definitions = pd.read_excel("/content/credit_data/Credit Data/Credit Data Definitions.xlsx")
credit_definitions

"""### Merging the credit data datasets"""

merged_credit_data = pd.concat([credit_data_jan,credit_data_march,credit_data_june,
                                credit_data_sep,credit_data_dec],ignore_index = "True")

merged_credit_data.sample(10)

"""### Dropping unnecessary columns"""

merged_credit_data = merged_credit_data.drop(columns=['Unnamed: 28'])
merged_credit_data.info()

"""### Calculating the percentage of null values in each column"""

merged_credit_data[['RETURN_DATE','PAYMENT_AMOUNT','ADJUSTMENT_AMOUNT','MAX_PAYMENT_DATE']]

"""#### Dealing with missing values"""

#Fill blank dates with 'Unknown' and blank amounts with '0'
merged_credit_data['RETURN_DATE'] = merged_credit_data['RETURN_DATE'].fillna('Unknown')
merged_credit_data['PAYMENT_AMOUNT'] = merged_credit_data['PAYMENT_AMOUNT'].fillna(0)
merged_credit_data['ADJUSTMENT_AMOUNT'] = merged_credit_data['ADJUSTMENT_AMOUNT'].fillna(0)
merged_credit_data['MAX_PAYMENT_DATE'] = merged_credit_data['MAX_PAYMENT_DATE'].fillna('Unknown')

"""### Converting date format

"""

merged_credit_data['DATE'] = pd.to_datetime(merged_credit_data['DATE'])

"""### Extracting month from date"""

merged_credit_data['Month'] = merged_credit_data['DATE'].dt.month_name()

merged_credit_data['Month'].value_counts()

"""### Checking for duplicates in Credit Data"""

# Count total duplicate rows across all months
duplicates_count = merged_credit_data.duplicated(subset=['Month', 'LOAN_ID']).sum()
print(f"Total duplicates found: {duplicates_count}")

# Count How many duplicates are in each month
duplicates_by_month = merged_credit_data[merged_credit_data.duplicated(subset=['Month', 'LOAN_ID'], keep=False)]
duplicates_by_month.groupby('Month')['LOAN_ID'].count()

merged_credit_data.duplicated().sum()

merged_credit_data.info()

"""### Reading Customer Sales Data"""

with zipfile.ZipFile('/content/Sales and Customer Data (1).zip', 'r') as zip_ref:
    zip_ref.extractall('customer_sales_data')

customer_sales_data = pd.read_excel("/content/customer_sales_data/Sales and Customer Data.xlsx")
customer_sales_data.head()

customer_sales_data.info()

"""### Renaming column name Loan Id"""

customer_sales_data = customer_sales_data.rename(columns={'Loan Id': 'Loan_ID'})

"""### Checking for missing values"""

# Calculate percentage of nulls
sales_null_pct = (customer_sales_data.isnull().sum() / len(customer_sales_data)) * 100

# Display the results
print(sales_null_pct)

# how many rows have no missing values
missing_customer_sales_data = customer_sales_data.isnull()
missing_customer_sales_data.sample(100)

# Check rows before dropping null values
print(f"Rows before:{len(customer_sales_data)}")

# Drops rows where all columns are blank
customer_sales_data = customer_sales_data.dropna(how="all")

#Check rows after dropping null values
print(f"Rows after:{len(customer_sales_data)}")

customer_sales_data.info()

# Checking rows where Loan_ID is blank
loan_id_blank = customer_sales_data['Loan_ID'].isnull()

# Filling blank Loan_ids with 'Unknown'
customer_sales_data['Loan_ID'] = customer_sales_data['Loan_ID'].fillna('Unknown')
customer_sales_data[loan_id_blank]

"""### Checking for duplicates"""

customer_sales_data.duplicated().sum()

customer_sales_data['Month'] = customer_sales_data['SALE_DATE'].dt.month_name()
customer_sales_data['Month'].value_counts()

# Count How many duplicates are in each month
duplicates_by_month_sales = customer_sales_data[customer_sales_data.duplicated(subset=['Month', 'Loan_ID'], keep="first")]
duplicates_by_month_sales.groupby('Month')['Loan_ID'].count()

"""### Reading NPS Data"""

nps_data = pd.read_excel("/content/NPS Data (1).xlsx")
nps_data.head()

nps_data.info()

"""### Cleaning column names"""

# Strip whitespace and convert to lowercase
nps_data.columns = nps_data.columns.str.strip().str.lower().str.replace(' ', '_')

nps_data

nps_data.info()

## Loan takers and the number of reviews left
duplicates_by_review = nps_data[nps_data.duplicated(subset=['loan_id'], keep="first")]

duplicates_by_loan_id = duplicates_by_review['loan_id'].value_counts()

duplicates_by_loan_id.head(20)

"""## Feature Engineering

### Creating Average Monthly Income band
"""

# Define income ranges
bins = [-1, 5000, 9999, 19999, 29999, 49999, 99999, 149999, float('inf')]
labels = ['Below 5,000', '5,000–9,999', '10,000–19,999', '20,000–29,999',
          '30,000–49,999', '50,000–99,999', '100,000–149,999', '150,000+']

# Calculate total income based on relevant columns
merged_credit_data['Total_income'] = merged_credit_data['TOTAL_PAID'] + merged_credit_data['PAYMENT_AMOUNT'] + merged_credit_data['ADVANCE']

merged_credit_data['Duration'] = (merged_credit_data['DATE'] - pd.to_datetime(merged_credit_data['SALE_DATE'])).dt.days

# Calculate average income
merged_credit_data['Average_Total_income'] = merged_credit_data['Total_income'] / merged_credit_data['Duration']

#Segmenting Income based on ranges
merged_credit_data['Income_Range'] = pd.cut(merged_credit_data['Average_Total_income'], bins=bins, labels=labels)

"""### Checking Days Past Due"""

print(merged_credit_data['DAYS_PAST_DUE'].isnull().sum())
print(merged_credit_data['DAYS_PAST_DUE'].dtype)

"""### Creating Customer Age Bands"""

# Define income ranges
age_bins = [18, 25, 35, 45, 55, float('inf')]
age_labels = ['18-25','26-35','36-45','46-55','55+']

#Segmenting Income based on ranges
merged_credit_data['Age_Range'] = pd.cut(merged_credit_data['CUSTOMER_AGE'], bins=age_bins, labels=age_labels)

merged_credit_data['Age_Range']

"""### Creating risk category"""

# Define the risk dictionary
risk_map = {
    'Existing Active': 'Low', 'New Active': 'Low', 'Paid Off Cash': 'Low',
    'Paid Off Loan': 'Low', 'Demo': 'Low', 'First 2 days Return': 'Low',

    'Inactive 01-07': 'Medium', 'Inactive 08-14': 'Medium', 'Inactive 15-30': 'Medium',

    'Blocked 31-60': 'High', 'Blocked 61-90': 'High',
    'First Month Default without inventory 01-07': 'High',
    'First Month Default without inventory 08-14': 'High',

    'Write Off': 'Critical', 'Lost Write Off': 'Critical',
    'First Payment Default': 'Critical', 'First Month Default with inventory': 'Critical',
    'First Month Default without inventory over 30': 'Critical',
    'Cancelled Returned past 3 mths': 'Critical', 'Cancelled Returned in 3 mths': 'Critical'
}

# 2. Apply the mapping to a new column
merged_credit_data['risk_category'] = merged_credit_data['ACCOUNT_STATUS_L1'].map(risk_map)

# 3. Check for any statuses that didn't get mapped (will show as NaN)
print(merged_credit_data['risk_category'].value_counts(dropna=False))